name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
        env:
          NEXT_PUBLIC_API_URL: https://llm-service.polymas.com/api/openai/v1/images/task/async
          NEXT_PUBLIC_API_KEY: sk-zAJCqOxm3vgTLgVVfAcXOmpL6jHoVRTqPjwxnBohLaiueIdk
          NEXT_PUBLIC_MODEL: dall-e-3
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: cfat_y4pkGWptkIj4turE0uYPQyZ8o0uD8YP1OjbuXxzX23100608
          accountId: 118d72a731155900747453dbb4e440a9
          command: pages deploy .next --project-name=image-style-transfer --branch=main
